<select id="<?php echo $id ?>" name="<?php echo \Zenchef\Widget\SETTINGS_OPTION_NAME ?>[<?php echo $id ?>]">
    <?php foreach ($options as $option_value => $option_label): ?>
        <option value="<?php echo $option_value ?>"<?php echo selected($value, $option_value, false) ?>><?php echo $option_label ?></option>
    <?php endforeach; ?>
</select>

<?php if($description !== ''): ?>
    <p class='description'><?php echo $description ?></p>
<?php endif; ?>
